# Generated by Django 5.2.8 on 2025-11-27 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epis',
            fields=[
                ('id_epis', models.AutoField(primary_key=True, serialize=False)),
                ('nome_epi', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_acessorio', models.CharField(blank=True, max_length=45, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=45, null=True)),
                ('data_validade', models.CharField(blank=True, max_length=45, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=45, null=True)),
                ('qtd_estoque', models.IntegerField(blank=True, default=0, null=True)),
                ('delete_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'Epis',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_setor', models.CharField(blank=True, max_length=45, null=True)),
                ('epis_necessario', models.CharField(blank=True, max_length=45, null=True)),
                ('delete_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'Setor',
            },
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_col', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('nome_colaborador', models.CharField(blank=True, max_length=155, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('tipo_colaborador', models.CharField(blank=True, max_length=30, null=True)),
                ('delete_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('epis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_site.epis')),
                ('quantidade_disponivel', models.IntegerField(blank=True, null=True)),
                ('delete_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('ddelete_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.colaboradores')),
                ('epis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.epis')),
            ],
            options={
                'db_table': 'Emprestimos',
                'constraints': [models.UniqueConstraint(fields=('colaborador', 'epis'), name='unique_colaborador_epis')],
            },
        ),
    ]
