# Generated by Django 5.2.7 on 2025-10-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epis',
            fields=[
                ('id_epis', models.AutoField(primary_key=True, serialize=False)),
                ('nome_epi', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_acessorio', models.CharField(blank=True, max_length=45, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=45, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=45, null=True)),
                ('delete', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'epis',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_setor', models.CharField(blank=True, max_length=45, null=True)),
                ('epis_necessario', models.CharField(blank=True, max_length=45, null=True)),
                ('delete', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'setor',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('epis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_site.epis')),
                ('quantidade_disponivel', models.IntegerField(blank=True, null=True)),
                ('delete', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'estoque',
            },
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_col', models.AutoField(primary_key=True, serialize=False)),
                ('nome_colaborador', models.CharField(blank=True, max_length=45, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('senha', models.CharField(blank=True, max_length=45, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('tipo_colaborador', models.CharField(blank=True, max_length=10, null=True)),
                ('delete', models.CharField(blank=True, max_length=1, null=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='app_site.setor')),
            ],
            options={
                'db_table': 'colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('delete', models.CharField(blank=True, max_length=1, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.colaboradores')),
                ('epis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.epis')),
            ],
            options={
                'db_table': 'emprestimos',
                'constraints': [models.UniqueConstraint(fields=('colaborador', 'epis'), name='unique_colaborador_epis')],
            },
        ),
    ]
