# Generated by Django 5.2.7 on 2025-10-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='setor',
            field=models.IntegerField(),
        ),
    ]
