# Generated by Django 5.2.8 on 2025-11-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0002_colaboradores_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='data_devolucao',
            new_name='data_devolver',
        ),
        migrations.RenameField(
            model_name='emprestimos',
            old_name='ddelete_flag',
            new_name='delete_flag',
        ),
        migrations.RenameField(
            model_name='emprestimos',
            old_name='epis',
            new_name='equipamento',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='data_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
