# Generated by Django 5.2.7 on 2025-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0002_alter_colaboradores_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='setor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
