# Generated by Django 5.2.7 on 2025-10-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0003_alter_colaboradores_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='setor',
            new_name='setor_id',
        ),
    ]
