# Generated by Django 5.2.8 on 2025-11-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0003_rename_data_devolucao_emprestimos_data_devolver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='equipamento',
            new_name='epis',
        ),
    ]
