# Generated by Django 5.2.8 on 2025-11-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0004_rename_equipamento_emprestimos_epis'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
