# Generated by Django 5.2.7 on 2025-10-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0004_rename_setor_colaboradores_setor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='setor_id',
            new_name='id_setor',
        ),
    ]
