# Generated by Django 5.2.8 on 2025-11-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0005_rename_setor_id_colaboradores_id_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='delete',
            new_name='delete_flag',
        ),
        migrations.RenameField(
            model_name='emprestimos',
            old_name='delete',
            new_name='ddelete_flag',
        ),
        migrations.RenameField(
            model_name='epis',
            old_name='delete',
            new_name='delete_flag',
        ),
        migrations.RenameField(
            model_name='setor',
            old_name='delete',
            new_name='delete_flag',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='id_setor',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='delete',
        ),
        migrations.AddField(
            model_name='estoque',
            name='delete_flag',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterModelTable(
            name='colaboradores',
            table='Colaboradores',
        ),
        migrations.AlterModelTable(
            name='emprestimos',
            table='Emprestimos',
        ),
        migrations.AlterModelTable(
            name='epis',
            table='Epis',
        ),
        migrations.AlterModelTable(
            name='estoque',
            table='Estoque',
        ),
        migrations.AlterModelTable(
            name='setor',
            table='Setor',
        ),
    ]
