# Generated by Django 5.2.8 on 2025-11-08 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0006_rename_delete_colaboradores_delete_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='id_setor',
            field=models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_site.setor'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_reserva', models.DateField(blank=True, null=True)),
                ('delete_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('colaborador', models.ForeignKey(db_column='id_col', on_delete=django.db.models.deletion.CASCADE, to='app_site.colaboradores')),
                ('epis', models.ForeignKey(db_column='id_epis', on_delete=django.db.models.deletion.CASCADE, to='app_site.epis')),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
    ]
