# Generated by Django 5.2.8 on 2025-11-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_remove_customuser_username_customuser_cpf'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
